### ISSUE TITLE
REFACTOR

### ISSUE THREAD

**Issue by ilovecherries** [y-ack/e#16]
things that need to be done
- [x] merging the editor and the interface into one
- [x] make WindowTree and Pane into one
- [x] create split pane function that can be used to easily generate branches
- [x] give every class a rust-doc i do not want to ever look at this in 5 years and be confused at what the fuck everything is

**Comment by ilovecherries** [comment]
ok umm i still need to figure out the issue of how im going to share buffers with the editor and the windows at the same time

**Comment by ilovecherries** [comment]
https://old.reddit.com/r/rust/comments/bsmv7p/building_a_vect_in_a_function_cannot_return_value/eoodoya/
https://github.com/y-ack/e/blob/5f52149cf3b3cde884b99a9fb922badb3e7f2b15/src/window.rs#L31
https://github.com/y-ack/e/blob/5f52149cf3b3cde884b99a9fb922badb3e7f2b15/src/buffer.rs#L129

we need to probably get the direct values of the items instead of references??? ill come to this in a bit

**Comment by ilovecherries** [comment]
from the looks of it, I /might/ have to contain the `Spans` in an `Rc`?

**Comment by ilovecherries** [comment]
I am moving rendering out of `Buffer`, it gives the buffer too much authority when the rendering of the buffer should be handled by external factors like the `Window`

**This does not include highlighting** right now, but I will eventually change the highlighting function to give back a vector of text with associated styles instead of having `Buffer` render all of the components.

**Comment by y-ack** [comment]
> I am moving rendering out of `Buffer`, it gives the buffer too much authority when the rendering of the buffer should be handled by external factors like the `Window`

sounds good to me
> **This does not include highlighting** right now, but I will eventually change the highlighting function to give back a vector of text with associated styles instead of having `Buffer` render all of the components.

highlighting can basically be done by anyone that has the tree, uh, if there's 
a implicit 'buffer provides highlighting info' then there's also the opportunity for buffer to cache highlighted info (e.g. for buffers that haven't actually updated they can just return the cache instead of rehighlighting, but the cache would only make sense to belong to buffer)

**Comment by ilovecherries** [comment]
i think this is fine to pull into, i think i should separate other problems into new issues
